extends: 
  - airbnb
  - prettier
plugins:
  - jsx-a11y
  - import
  - react
  - react-native
  - prettier
rules:
  quotes:
    - warn
    - single
  indent:
    - error
    - 2
  react/sort-comp: warn
  react-native/no-unused-styles: error
  react-native/no-color-literals: off
  react-native/split-platform-components: off
  react-native/no-inline-styles: warn
  linebreak-style: off
  no-undef: error
  prettier/prettier: error
settings:
  import/resolver: reactnative
