extends: 
  - airbnb
  - prettier
  - plugin:jest/recommended
plugins:
  - jsx-a11y
  - import
  - react
  - react-native
  - prettier
  - jest
rules:
  quotes:
    - warn
    - double
  indent:
    - error
    - 2
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
  react/sort-comp: warn
  react-native/no-unused-styles: error
  react-native/no-color-literals: off
  react-native/split-platform-components: off
  react-native/no-inline-styles: warn
  linebreak-style: off
  no-undef: error
  prettier/prettier: error
settings:
  import/resolver: reactnative
env:
  jest/globals: true
