version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing yarn
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}`Preformatted text`
      - run:
          name: Create ENV
          command: cp src/main/js/env.js.sample src/main/js/env.js
      - run:
          name: Running Lint Tests
          command: yarn run lint

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Create ENV
          command: cp src/main/js/env.js.sample src/main/js/env.js
      - run:
          name: Installing yarn
          command: yarn install
      - run:
          name: Installing exp
          command: yarn global add exp
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Deploying to Expo
          command: |
            export PATH="$PATH:$( yarn global bin )"
            exp login --username $EXPO_USER_NAME --password $EXPO_PASSWORD
            exp publish --non-interactive

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
